[package]
name = "data_structure"
version = "0.1.0"
authors = ["Yufei-YAO <67418461+Yufei-YAO@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit_field = "0.10.0"